---
title: "Mario"
author: "Mario"
date: '2020-11-02'
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(tidyverse)
library(dplyr)
library(vegan)
library(emmeans)
setwd("/R Packages/Magic The Gathering")
```

## Load Magic Dataset
The following dataset was compiled by opening 15 draft booster boxes from recent Magic the Gathering Standard sets. 5 Boxes of Ikoria: Lair of Behemoths, 5 of Core 2021, and 5 of Zendikar Rising. Packs were opened and all cards inputted for the exception of tokens and basic land cards.
```{r cars}
MTG <- read.csv("MTG_data.csv")
MTG <- MTG %>%
  group_by(set, rep, card_name, rarity, card_type, finish, n, price) %>%
  summarise(total = sum(n))
MTG_norep <- MTG %>%
  group_by(set, card_name, rarity, card_type, finish, n, price) %>%
  summarise(total = sum(n))
```

##Vegan Set-up
```{r}
###Group main Data by Set, Rarity, Card Type, Finish, Total number and Price. Rep was removed from this dataset.
MTG_Vegan <- MTG_norep %>%
  group_by(set, rarity, card_type, card_name, finish, total, price) 

MTG_Vegan$rarity <- gsub(" ", "", MTG_Vegan$rarity)
MTG_Vegan$rarity <- as.factor(MTG_Vegan$rarity)
MTG_Vegan$uniID <- paste(MTG_Vegan$set, MTG_Vegan$rarity)
str(MTG_Vegan)

###Ungroup all and select the Unique ID, n, and total of specific card per box
library(dplyr)
MTG_Vegan <- MTG_Vegan %>% 
  ungroup()%>%
  dplyr::select(uniID, n, total)
MTG_Vegan <- MTG_Vegan %>% group_by(uniID, total) %>% summarise(Total = sum(n))

MTG_Vegan
###Spread the Data
commMTG <- MTG_Vegan %>% spread(total, Total)
commMTG[is.na(commMTG)] <- 0

##Drop Unique ID
commMTG <- commMTG %>%
  ungroup() %>%
  dplyr::select(-uniID)

commMTG

##Set up a mini-dataset to join the calculations to after. This dataset broken up by set and rarity.
setMTG <- MTG %>%
  group_by(set, rarity) %>%
  summarise(Total = sum(n))

setMTG$Total <- gsub(" ", "", setMTG$Total)
setMTG$Total <- as.factor(setMTG$Total)
setMTG$uniID <- paste(setMTG$set, setMTG$rarity)
str(setMTG)

setMTG <- setMTG %>%
  ungroup()%>%
  dplyr::select(uniID, set, rarity, Total)
setMTG <- setMTG %>% group_by(uniID, rarity)

setMTG <- setMTG %>%
  ungroup() %>%
  dplyr::select(-uniID)

##Run Simpsons test and Evenness for community data
##Note: Since many Mythics were only pulled ONCE during openings, many of the Simpsons and evenness calculations for Mythic cards result in either a 0 or NA
simpsonfinal <- diversity(commMTG, index = "simpson")
Hfinal <- diversity(commMTG)
Sfinal <- specnumber(commMTG)
Evenness <- Hfinal/log(Sfinal) 
setMTG$Simpson <- simpsonfinal
setMTG$Evenness <- Evenness

##Merge Data back to the main dataset
finalMTG <- merge(MTG_norep, setMTG)
```
###Data Viz
```{r}
###Figure showing Total cards rarities pulled by set
count <- ggplot(setMTG, aes(set, Total, fill = set)) +
  geom_histogram(stat = "identity") +
  facet_wrap(~rarity) +
  scale_color_brewer(palette = "Set1") + theme_classic() + 
  geom_smooth(method = lm, se = TRUE) + 
  labs(x = "Set", y = "Total Cards by Rarity")
count
```
```{r}
type <- ggplot(finalMTG, aes(card_type, total, fill = set)) +
  geom_histogram(stat = "identity") +
  facet_wrap(~rarity) +
  theme_classic() + 
  theme(axis.text.x = element_text( 
                           size = 12, angle = 90))+
  geom_smooth(method = lm, se = TRUE) + 
  labs(x = "Card Type", y = "Total Cards by Card Type")
type
```
```{r}
cardtype <- finalMTG %>%
 group_by(set, rarity, card_type, n) %>%
  summarise(total_type = sum(total), n = n()) 

###Displays all card types pulled in each set
ggplot(cardtype, aes(card_type, n, fill = set)) +
  geom_bar(stat = "identity") +
  coord_flip() + 
  labs(fill = "", x = "Card Type", y = "Total Number of Cards")


###Displays all card types pulled in each set by Rarity
ggplot(cardtype, aes(card_type, n, fill = rarity)) +
  geom_bar(stat = "identity") +
  facet_wrap(~set) +
  coord_flip() + 
  labs(fill = "", x = "Card Type", y = "Total Number of Cards")
 

```

```{r}
ggplot(cardtype, aes(card_type, total_type, fill = set)) +
  geom_bar(stat = "identity") +
  coord_flip() + 
  labs(fill = "", x = "Card Type", y = "Total Number of Cards")
```



```{r}
##Total rarity by evenness
Evenness <- ggplot(finalMTG, aes(total, Evenness, color = rarity)) + 
  geom_point(size = 1.5) +
  facet_wrap(~set) +
  scale_color_brewer(palette = "Set1") + theme_classic() + 
  geom_smooth(method = lm, se = TRUE) + 
  labs(x = "Box Number", y = "Evenness")
Evenness

###Total rarity by simpsons index
Richness <- ggplot(finalMTG, aes(total, Simpson, color = rarity)) + 
  geom_point(size = 1.5) +
  facet_wrap(~set) +
  scale_color_brewer(palette = "Set1") + theme_classic() + 
  geom_smooth(method = lm, se = TRUE) + 
  labs(x = "Box Number", y = "Simpson Index")
Richness
```
###Stats
```{r}
m1 <- glm(Evenness ~ set*rarity, family = "quasipoisson", data = finalMTG)
anova(m1, test = "Chisq")
e1 <- emmeans(m1, pairwise~set|rarity)
e1
```
